# Generated by Django 4.0.3 on 2022-04-02 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webb', '0004_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
